In [68]:
import numpy as np
import pandas as pd
import yfinance as yf
import sys
sys.path.insert(0, "/Users/giovanafalcao/Desktop/Projects/trading-analytics")
from utils import yfinance_fix

TICKER = "AAPL"
BM_TICKER = "^GSPC" # Benchmark Ticker: S&P 500  
INTERVAL = "1d"
PERIOD = "730d" if INTERVAL == "1D" else "max"
SHIFT = 1
LOOKBACK = 10000

# Step 1: Fetch historical price (time-series) data, compute change, return and log return

def fetch_price_data(ticker = TICKER, interval = INTERVAL, period = PERIOD, shift = SHIFT, lookback = LOOKBACK):
    df = yf.download(ticker, session=yfinance_fix.chrome_session, interval = interval, period = period)
    df.columns = df.columns.get_level_values(0)
    df = df.reset_index(drop=True)   

    return df.iloc[-lookback:, :]

df = fetch_price_data()
df

[*********************100%***********************]  1 of 1 completed

Price       Close        High         Low        Open     Volume
1427     0.106418    0.109837    0.105991    0.109837  185203200
1428     0.108555    0.111546    0.106418    0.106418  173398400
1429     0.108127    0.110692    0.108127    0.108982  110140800
1430     0.114538    0.114538    0.108555    0.108982  183433600
1431     0.117103    0.117530    0.114111    0.114111  244160000
...           ...         ...         ...         ...        ...
11422  260.480011  262.190002  259.019989  259.980011   31291500
11423  259.200012  260.179993  256.660004  259.730011   36234700
11424  258.829987  261.929993  257.190002  259.250000   48370700
11425  266.429993  266.559998  257.809998  258.160004   49735000
11426  262.500000  267.160004  261.309998  266.799988   10488574

[10000 rows x 5 columns]

In [69]:
# Step 2: Fetch Benchmark data for stocks in the same sector or industry

def fetch_benchmark_data(ticker = BM_TICKER,  interval = INTERVAL, period = PERIOD, lookback = LOOKBACK):
    df_bm = yf.download(ticker, session=yfinance_fix.chrome_session, interval = interval, period = period)
    df_bm.columns = df_bm.columns.get_level_values(0)
    return df_bm.iloc[-lookback:, :]

df_bm = fetch_benchmark_data()
df_bm

[*********************100%***********************]  1 of 1 completed

Price             Close         High          Low         Open      Volume
Date
1986-08-06   236.839996   237.350006   235.479996   237.029999   127500000
1986-08-07   237.039993   238.020004   236.309998   236.839996   122400000
1986-08-08   236.880005   238.059998   236.369995   237.039993   106300000
1986-08-11   240.679993   241.199997   236.869995   236.880005   125600000
1986-08-12   243.339996   243.369995   240.350006   240.679993   131700000
...                 ...          ...          ...          ...         ...
2026-04-10  6816.890137  6845.770020  6808.459961  6839.240234  4393220000
2026-04-13  6886.240234  6887.000000  6790.020020  6806.470215  4785840000
2026-04-14  6967.379883  6969.419922  6905.169922  6910.200195  5032380000
2026-04-15  7022.950195  7026.240234  6967.129883  6978.169922  5278610000
2026-04-16  7048.109863  7048.790039  7008.520020  7037.779785  1124371000

[10000 rows x 5 columns]